CREATE TABLE books (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
)

CREATE TABLE cities (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
city_name VARCHAR(30) NOT NULL,
)
